site_name: Documentation
repo_url: ""
edit_uri: ""
#site_url: "https://test-lumi-supercomputer-docs.rahtiapp.fi/" #hasn't been chosen yet
site_description: >-
  Instructions, user guides and tutorials for the use of the LUMI supercomputer
copyright: Copyright &copy; 2021 LUMI User Support Team
nav:
  - Home: 
    - Welcome: index.md
  - First steps: 
    - Get Started: firststeps/index.md
    - Access to LUMI: firststeps/accessLUMI.md
    - Setting up SSH key pair: firststeps/SSH-keys.md
    - Logging in (with SSH client): firststeps/loggingin.md
    - Logging in (with web interface): firststeps/loggingin-webui.md
    - Moving data to/from LUMI: firststeps/movingdata.md
    - Next steps: firststeps/nextsteps.md
  - Hardware:
    - Overview: hardware/index.md
    - GPU nodes - LUMI-G: hardware/lumig.md
    - CPU nodes - LUMI-C: hardware/lumic.md
    - Data analytics nodes - LUMI-D: hardware/lumid.md
    - Network and interconnect: hardware/network.md
  - Run jobs:
    - Overview: runjobs/index.md
    - Web interface:
      - Introduction: runjobs/webui/index.md
      - Interactive applications:
        - Overview: runjobs/webui/interactive-apps.md
        - Desktop: runjobs/webui/desktop.md
        - Julia-Jupyter: runjobs/webui/julia-jupyter.md
        - Jupyter: runjobs/webui/jupyter.md
        - Jupyter for courses: runjobs/webui/jupyter-for-courses.md
        - MLflow: runjobs/webui/mlflow.md
        - TensorBoard: runjobs/webui/tensorboard.md
        - Visual Studio Code: runjobs/webui/vscode.md
    - LUMI environment:
      - Module environment: runjobs/lumi_env/Lmod_modules.md
      - Software stacks: runjobs/lumi_env/softwarestacks.md
      - Daily management: runjobs/lumi_env/dailymanagement.md
      - Data storage options: storage/index.md
      - Billing policy: runjobs/lumi_env/billing.md
    - Batch jobs:
      - Slurm quickstart: runjobs/scheduled-jobs/slurm-quickstart.md
      - Slurm partitions: runjobs/scheduled-jobs/partitions.md
      - Batch jobs: runjobs/scheduled-jobs/batch-job.md
      - Full machine runs: runjobs/scheduled-jobs/hero-runs.md
      - GPU examples: runjobs/scheduled-jobs/lumig-job.md
      - CPU examples: runjobs/scheduled-jobs/lumic-job.md
      - Distribution and binding: runjobs/scheduled-jobs/distribution-binding.md
      - Job array: runjobs/scheduled-jobs/throughput.md
      - Interactive jobs: runjobs/scheduled-jobs/interactive.md
      - Container jobs: runjobs/scheduled-jobs/container-jobs.md
      - Julia scheduled jobs: runjobs/scheduled-jobs/julia.md
      - Energy consumption: runjobs/scheduled-jobs/jobenergy.md
  - Software:
    - Overview: software/index.md
    - Install policy: software/policy.md
    - Installing software:
      - EasyBuild: software/installing/easybuild.md
      - Spack: software/installing/spack.md
      - Python packages: software/installing/python.md
      - LUMI container wrapper: software/installing/container-wrapper.md
    - Containers: 
      - Singularity/Apptainer: software/containers/singularity.md
    - Software guides:
      - Software library: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/
      #- CP2K: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/c/CP2K/
      #- PyTorch: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/p/PyTorch/
      #- QuantumESPRESSO: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/q/QuantumESPRESSO/
      #- VASP: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/v/VASP/
    - Local software collections:
      - CSC: software/local/csc.md
      - CSC_quantum: software/local/csc-quantum.md
      #- Quantum ESPRESSO: software/guides/quantumespresso.md
      #- ParaView: software/guides/paraview.md
      #- Quantum ESPRESSO: software/guides/quantumespresso.md
      #- VASP: software/guides/vasp.md
  - Developing:
    - Overview: development/index.md
    - Compiling:
      - Programming environment: development/compiling/prgenv.md
      - Cray compilers: development/compiling/cce.md
      - GNU compilers: development/compiling/gnu.md
    - High performance libraries: 
      - Cray libraries: development/libraries/cray-libraries.md
    - Optimizing for LUMI:
      - Using hugepages: development/optimizing/hugepages.md
    - Debugging:
      - Parallel debugging: development/debugging/gdb4hpc.md
      - Memory debugging: development/debugging/valgrind4hpc.md
      - Crash or deadlock: development/debugging/stat-atp.md
    - Performance analysis:
      - Performance analysis strategies: development/profiling/strategies.md
      - Cray Performance Analysis Tool: development/profiling/perftools.md
  - Storage:
    - Overview: storage/index.md
    - Parallel filesystems:
      - Lustre: storage/parallel-filesystems/lustre.md
      - Main storage - LUMI-P: storage/parallel-filesystems/lumip.md
      - Flash storage - LUMI-F: storage/parallel-filesystems/lumif.md
    - Object storage:
      - LUMI-O usage: storage/lumio/index.md
      - Authentication for LUMI-O: storage/lumio/auth-lumidata-eu.md
      - Error messages: storage/lumio/error-messages.md
      - Advanced usage of LUMI-O: storage/lumio/advanced.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - LUMI training materials: https://lumi-supercomputer.github.io/LUMI-training-materials
    - LUMI AI Guide: https://github.com/Lumi-supercomputer/LUMI-AI-Guide
  - Help desk: 
    - Help desk: helpdesk/index.md
    - Training and events: helpdesk/training.md
    - Known issues: helpdesk/issues.md
    - LUMI service status: https://www.lumi-supercomputer.eu/lumi-service-status/
    - Mailing list archive: https://postit.csc.fi/sympa/arc/lumi-users
    
 
theme:
  name: material
  greetings: Welcome to the LUMI Documentation
  custom_dir: mkdocs_lumi/
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
  
  palette:
    scheme: default
    primary: lumi
    accent: lumi

  font: false
  
  favicon: assets/favicon.png

  icon:
    logo: logo
  
  home_primary:
    title: Get Started
    page: firststeps/getstarted/
  home_secondary:
    title: To LUMI Main Page
    page: https://lumi-supercomputer.eu/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lumi-supercomputer/lumi-userguide/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - redirects:
      redirect_maps:
        'computing/Lmod_modules.md': 'runjobs/lumi_env/Lmod_modules.md'
        'firststeps/getstarted.md': 'firststeps/index.md'
        'software/packages/pytorch.md': 'https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/p/PyTorch/'
  - search
